policy-enforcer-config:
  paths:
    - path: /api/produto/*
      methods:
        - method: GET
          scopes: ["view"]
        - method: POST
          scopes: ["create"]
    - path: /api/produto/{id}
      methods:
        - method: GET
          scopes: ["view"]
        - method: PUT
          scopes: ["update"]
        - method: DELETE
          scopes: ["delete"]
