spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
    # database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: refactorsistemasenac
    password: refactorsistemasenac
