server:
  port: 8081
  servlet:
    context-path: /itemflow
  error:
    include-message: always
spring:
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
    # database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        use_sql_comments: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: refactorsistemasenac
    password: refactorsistemasenac
logging:
  level:
    br:
      jus: ${LOGGING_LEVEL:DEBUG}
    org:
      keycloak: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
        security: INFO
security:
  oauth2:
    client:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/itemflow
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#        registration:
#          external:
#            provider: external
#            client-name: itemflow
#            client-id: itemflow-backend
#            client-secret: 8YfAMQFSkKq0ADBPiPrmF0Gt5grR02IF
#            scope: openid, offline_access, profile
#            authorization-grant-type: authorization_code
