server:
  port: 8081
  servlet:
    context-path: /stox
  error:
    include-message: always
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: plataforma-database-pool
      auto-commit: false
      connection-timeout: 30000
    url: "jdbc:postgresql://localhost:5432/stox"
    username: postgres
    password: stox
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
logging:
  level:
    org.springframework.web: DEBUG
#keycloak:
#  realm: stox
#  auth-server-url: http://localhost:8080/auth
#  ssl-required: external
#  resource: stox-backend
#  use-resource-role-mappings: true
#  bearer-only: true



